services:
  - type: web
    name: spring-boot-app
    env: java
    buildCommand: mvn clean install
    startCommand: java -jar target/SEBDM_pro-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SUPABASE_URL
        value: jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres
      - key: SUPABASE_DB_USERNAME
        value: postgres.wxeseejwtrlkyitubugy
      - key: SUPABASE_DB_PASSWORD
        value: dRWMSfNPgGDv3lxk
